_target_: src.models.bats_module.BatsLitModule

optimizer:
  _target_: torch.optim.AdamW
  _partial_: true
  lr: 0.00007
  weight_decay: 0.001

scheduler:
  _target_: torch.optim.lr_scheduler.OneCycleLR
  _partial_: true
  max_lr: 0.0003
  epochs: 10
  steps_per_epoch: 1508
net:
  _target_: src.models.components.efficientnet.EfficientNet
  num_classes: 12
  pretrained: true

# compile model for faster training with pytorch 2.0
compile: false
